FROM python:3.8.12-slim

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./project/jobs ./project/jobs
COPY ./project/__init__.py ./project
COPY requirements.jobs .
RUN pip install -r requirements.jobs

