name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd demo-01_docker && docker build . --file Dockerfile --tag demo-01-docker:$(date +%s)
        cd ../demo-02_multi-queue && docker build . --file Dockerfile --tag demo-02-docker:$(date +%s)
        cd ../demo-03_recurring-tasks && docker build . --file Dockerfile --tag demo-03-docker:$(date +%s)
      
